# Generated by Django 5.2.1 on 2025-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=200)),
                ('publication_year', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
